#!/usr/bin/env python
# Author: "Chris Ward <cward@redhat.com>

from functools import partial
from pprint import PrettyPrinter
pp = PrettyPrinter(indent=2)

from metrique.client import pyclient

prompter = lambda x: raw_input(x)

c = pyclient()

c.config._autosave = False

pp.pprint(c.config._config)

_p = "Metrique Host: "
c.config.setup_basic('api_host', partial(prompter, _p))

_p = "Metrique Username: "
c.config.setup_basic('api_username', partial(prompter, _p))

_p = "Metrique Password: "
c.config.setup_basic('api_password', partial(prompter, _p))

pp.pprint(c.config._config)

a = c.config.yes_no_prompt('Save? ')
if a:
    c.config.save()
